-- COPY raw files from the external stage into bronze tables.
-- Snowflake load history makes this idempotent: already-loaded files are skipped.
USE ROLE SYSADMIN;
USE DATABASE STEAM;
USE SCHEMA OPS;

CREATE OR REPLACE PROCEDURE OPS.LOAD_RAW()
  RETURNS STRING
  LANGUAGE SQL
AS
$$
BEGIN
  COPY INTO RAW.MOST_PLAYED (payload, _file)
    FROM (SELECT $1, METADATA$FILENAME FROM @OPS.STEAM_RAW_STAGE/most_played/)
    FILE_FORMAT = (FORMAT_NAME = OPS.NDJSON_FMT) ON_ERROR = 'ABORT_STATEMENT';

  COPY INTO RAW.PLAYER_COUNTS (payload, _file)
    FROM (SELECT $1, METADATA$FILENAME FROM @OPS.STEAM_RAW_STAGE/player_counts/)
    FILE_FORMAT = (FORMAT_NAME = OPS.NDJSON_FMT) ON_ERROR = 'ABORT_STATEMENT';

  COPY INTO RAW.REVIEWS (payload, _file)
    FROM (SELECT $1, METADATA$FILENAME FROM @OPS.STEAM_RAW_STAGE/reviews/)
    FILE_FORMAT = (FORMAT_NAME = OPS.NDJSON_FMT) ON_ERROR = 'ABORT_STATEMENT';

  COPY INTO RAW.APP_DETAILS (payload, _file)
    FROM (SELECT $1, METADATA$FILENAME FROM @OPS.STEAM_RAW_STAGE/app_details/)
    FILE_FORMAT = (FORMAT_NAME = OPS.NDJSON_FMT) ON_ERROR = 'ABORT_STATEMENT';

  RETURN 'raw load complete';
END;
$$;

-- Smoke test:
-- CALL OPS.LOAD_RAW();
-- SELECT COUNT(*) FROM RAW.REVIEWS;
