-- Run as SYSADMIN (or ACCOUNTADMIN on a trial account)
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS STEAM_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STEAM;
CREATE SCHEMA IF NOT EXISTS STEAM.RAW;     -- bronze: raw VARIANT landing tables
CREATE SCHEMA IF NOT EXISTS STEAM.SILVER;  -- dbt: cleaned/typed models
CREATE SCHEMA IF NOT EXISTS STEAM.GOLD;    -- dbt: facts and dimensions
CREATE SCHEMA IF NOT EXISTS STEAM.OPS;     -- procs, tasks, file formats
