USE ROLE SYSADMIN;
USE DATABASE STEAM;
USE WAREHOUSE STEAM_WH;

CREATE OR REPLACE FILE FORMAT OPS.NDJSON_FMT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE OPS.STEAM_RAW_STAGE
  URL = 's3://portfolio-steam-data-raw/raw/'
  STORAGE_INTEGRATION = steam_s3_int
  FILE_FORMAT = OPS.NDJSON_FMT;

-- Bronze landing tables: one VARIANT column + load metadata
CREATE TABLE IF NOT EXISTS RAW.MOST_PLAYED   (payload VARIANT, _file STRING, _loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS RAW.APP_DETAILS   (payload VARIANT, _file STRING, _loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS RAW.REVIEWS       (payload VARIANT, _file STRING, _loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS RAW.PLAYER_COUNTS (payload VARIANT, _file STRING, _loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP());

-- Sanity check after the extractor has run at least once:
-- LIST @OPS.STEAM_RAW_STAGE;
